version: "3.9" 
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5673:5673"
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: CIPlatform
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  webapi:
    build: src/CIPlatformWebAPI
    ports:
      - "5100:5100"
  manager:
    build: src/CIPlatformManager
    ports:
      - ""
  worker:
    build: src/CIPlatformWorker
    ports:
      - ""
    privileged: true
    volumes:
      - /var.run/docker.sock:/var/run/docker.sock

volumes:
  logvolume: {}